fyp/fyp/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('project/',include('project.urls')),
    path('', user_views.index, name='home'),
]

fyp/project/urls.py
from django.urls import path
from . import views
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views

app_name = 'project'

urlpatterns = [
    path('new', views.ProjectCreateView, name='create'),
    path('list/<str:username>',views.ProjectListView.as_view(), name='list'),
    path('plot/<int:pk>/',views.plotGraph, name='create-plot'),
    path('read/<int:pk>', views.read_data, name='read'),
    path('<int:pk>/', views.plotList, name='plot-list'),
    path('<int:pk>/<int:plotpk>/', views.viewPlot, name='view-plot'),
    path('dashboard/<int:pk>/', views.dashboard, name='dashboard'),
    path('<int:pk>/delete/', views.projectDeleteView.as_view(), name='project-delete'),
    path('plot/<int:pk>/delete/', views.plotDeleteView.as_view(), name='plot-delete'),
    path('edit/<int:pk>/<int:plotpk>', views.editPlot, name='edit-plot')
    # path('graph/<int:pk>/',views.get_data, name="test")
]

fyp/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('upload/', views.upload_datafiles, name='upload'),
    path('read/', views.read_data, name='read'),
    path('test/', views.test, name='test'),
]

fyp/project/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=150)
    pub_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Dataset(models.Model):
    dataset = models.FileField(upload_to='datasets/',default="")
    project = models.OneToOneField(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    columns = models.TextField()
    size = models.CharField(max_length=100)

    def __str__(self):
        return self.title
    
    def delete(self, *args, **kwargs):
        self.dataset.delete()
        super().delete(*args, **kwargs)

class Plot(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    columns = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    plottype = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    
    def __str__(self):
        return self.title
        

fyp/project/forms.py
from django import forms
from .models import Project, Dataset

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description']

class DataForm(forms.ModelForm):
    class Meta:
        model = Dataset
        fields = ['dataset']

fyp/project/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.urls import reverse
from .models import Project, Dataset, Plot
from .forms import ProjectForm, DataForm
from django import forms
from django.forms import formset_factory
from bokeh.plotting import figure
from bokeh.embed import components
from bokeh.models import HoverTool, ColumnDataSource, CDSView, Line
from bokeh.palettes import Spectral3, Spectral5, Category10
from bokeh.transform import factor_cmap
from bokeh.document import Document
from django.views.generic import (
	ListView, 
	DetailView,
	CreateView,
	UpdateView,
	DeleteView

)

import numpy as np
import pandas as pd
import ast
import boto3
import os
from smart_open import smart_open

# Create your views here.

class ProjectListView(ListView):
    model = Project
    template_name = 'project/list.html'
    context_object_name = 'projects'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Project.objects.filter(author=user)
@login_required
def ProjectCreateView(request):
    if request.method == "POST":
        p_form = ProjectForm(request.POST)
        d_form = DataForm(request.POST, request.FILES)

        if p_form.is_valid() and d_form.is_valid():
            uploaded_files = request.FILES['dataset']
            df = pd.read_csv(uploaded_files)
            Project = p_form.save(False)
            Project.author = request.user
            Project.save()
            Dataset = d_form.save(False)

            Dataset.title = uploaded_files.name
            Dataset.size = uploaded_files.size
            Dataset.columns = df.columns.str.strip().str.replace(' ','_')
            Dataset.project = Project
            Dataset.save()
            
            return redirect(reverse('project:plot-list', kwargs={'pk': Project.pk}))
    else:
        p_form = ProjectForm
        d_form = DataForm

    return render(request, 'project/newproject.html', {'dataform' : p_form, 'projectform' : d_form})

def plotGraph(request, pk):

    #----------------------import data--------------------------
    data = Dataset.objects.get(project=pk)
    plots = Plot.objects.filter(project=pk)
    title = data.title
    #--------readfilefroms3------------#
    aws_key = os.environ['AWS_ACCESS_KEY_ID']
    aws_secret = os.environ['AWS_SECRET_ACCESS_KEY']
    bucket_name = os.environ['AWS_STORAGE_BUCKET_NAME']
    client = boto3.client('s3')
    path = 's3://{}:{}@{}/datasets/{}'.format(aws_key, aws_secret, bucket_name, title)
    df = pd.read_csv(smart_open(path))
    # df = pd.read_csv(f'media/datasets/{title}')
    df[df.columns[0]] = pd.to_datetime(df[df.columns[0]])
    df.columns = df.columns.str.strip().str.replace(' ','_')
    dateindex = df.columns.values[0]
    print(df)

    #-------------Create tuple pairs for choicefield---------------------
    choicelist = df.columns.values.tolist()
    choicelist2 = choicelist
    choice = list(zip(choicelist,choicelist2))
    print(choice)
    #------------------Create form------------------------------------
    class LineForm(forms.Form):
        Title = forms.CharField()
        Y = forms.ChoiceField(choices=choice)
        Description = forms.CharField(widget=forms.Textarea)

    class LineForm2(forms.Form):
        Title = forms.CharField()
        Y = forms.ChoiceField(choices=choice)
        Y2 = forms.ChoiceField(choices=choice)
        Description = forms.CharField(widget=forms.Textarea)

    form = LineForm()
    form2 = LineForm2()

    # class BarChartForm(forms.Form):
    #     Y = forms.ChoiceField(choices=choice)
    #     X = forms.ChoiceField(choices=choice)
    # form3 = BarChartForm()
    
    #-----------------------------CreatePlot--------------------------#
    
    if request.method == 'POST' and 'createdouble' in request.POST:
        form2 = LineForm2(request.POST)
        if form2.is_valid():
            print('doubleline')
            source = ColumnDataSource(df)
            TOOLS = 'save,pan,box_zoom,reset,wheel_zoom'
            p = figure(
                title= form2.cleaned_data['Title'],
                x_axis_type='datetime', 
                tools=TOOLS, 
                plot_height=400, 
                plot_width=700,
                )
            p.xaxis.axis_label = 'Time'
            p.left[0].formatter.use_scientific = False
            # p.yaxis.axis_label = form.cleaned_data['Y']
            view = CDSView(source=source, filters=[])
            y = form2.cleaned_data['Y']
            y2 = form2.cleaned_data['Y2']
            # p.multi_line(xs="xs", ys="ys", source=source, line_color="color",legend_group='group', view=view, line_width=2)
            line1 = p.line(x=df.columns.values[0], y=y, source=source, color=Spectral3[0], legend_label=y, view=view)
            line2 = p.line(x=df.columns.values[0], y=y2, source=source, color=Spectral3[2], legend_label=y2, view=view)
            line2 = p.line(x=df.columns.values[0], y=y, source=source, alpha = 0)
            hover = HoverTool(
                tooltips = [
                    ('Date', f'@{dateindex}''{%F}'),
                    (f"{form2.cleaned_data['Y']}", f"@{form2.cleaned_data['Y']}"'{int}'),
                    (f"{form2.cleaned_data['Y2']}", f"@{form2.cleaned_data['Y2']}"'{int}'),
                ],
                formatters={
                    f'@{dateindex}': 'datetime',
                },
                mode='vline',
                renderers=[line1]
            )
            p.add_tools(hover)
            script, div = components(p) 
            return render(request, 'project/test.html', {'script': script, 'div':div, 'form':form, 'form2':form2, 'type':'Double', 'data':data})


    if request.method == 'POST' and 'createsingle' in request.POST:
        form = LineForm(request.POST)
        if form.is_valid():
            source = ColumnDataSource(df)
            print('singleline')
            TOOLS = 'save,pan,box_zoom,reset,wheel_zoom'
            p = figure(
                title= form.cleaned_data['Title'],
                x_axis_type='datetime', 
                tools=TOOLS, 
                plot_height=400, 
                plot_width=700,
                )
            p.xaxis.axis_label = 'Time'
            p.left[0].formatter.use_scientific = False
            p.yaxis.axis_label = form.cleaned_data['Y']
            view = CDSView(source=source, filters=[])
            hover = HoverTool(
                tooltips = [
                    ('Date', f'@{dateindex}''{%F}'),
                    (f"{form.cleaned_data['Y']}", f"@{form.cleaned_data['Y']}"'{int}'),
                ],
                formatters={
                    f'@{dateindex}': 'datetime',
                },
                mode='vline'
            )
            p.add_tools(hover)
            p.line(x=df.columns.values[0], y=form.cleaned_data['Y'], source=source, view=view)
            script, div = components(p)
            return render(request, 'project/test.html', {'script': script, 'div':div, 'form':form, 'form2':form2, 'type':'Single', 'data':data})
    
    #------------------------------SavePlot-----------------------------------------#

    if request.method == 'POST' and 'savesingle' in request.POST:
        form = LineForm(request.POST)
        if form.is_valid():
            plottype = 'Single'
            plot = Plot()
            plot.project = Project.objects.get(id=pk)
            plot.title = form.cleaned_data['Title']
            plot.columns = form.cleaned_data['Y']
            plot.description = form.cleaned_data['Description']
            plot.plottype = plottype
            plot.save()
            # return render(request, 'project/test.html', {'form':form,'form2':form2, 'data':data})
            return render(request, 'project/plotlist.html', {'plots': plots, 'projectid': pk, 'data':data})

    if request.method == 'POST' and 'savedouble' in request.POST:
        form2 = LineForm2(request.POST)
        if form2.is_valid():
            plottype = 'Double'
            plot = Plot()
            plot.project = Project.objects.get(id=pk)
            plot.title = form2.cleaned_data['Title']
            plot.columns = [form2.cleaned_data['Y'], form2.cleaned_data['Y2']]
            plot.plottype = plottype
            plot.description = form2.cleaned_data['Description']
            plot.save()
            # return render(request, 'project/test.html', {'form':form,'form2':form2, 'data':data})
            return render(request, 'project/plotlist.html', {'plots': plots, 'projectid': pk, 'data':data})
   
    return render(request, 'project/test.html', {'form':form,'form2':form2, 'data':data})

def editPlot(request, pk, plotpk):
    #----------------------import data--------------------------
    data = Dataset.objects.get(project=pk)
    plots = Plot.objects.filter(project=pk) #--------projectplot---------
    currentplot = Plot.objects.get(id=plotpk) #--------currentplot--------
    title = data.title
    #--------readfilefroms3------------#
    aws_key = os.environ['AWS_ACCESS_KEY_ID']
    aws_secret = os.environ['AWS_SECRET_ACCESS_KEY']
    bucket_name = os.environ['AWS_STORAGE_BUCKET_NAME']
    client = boto3.client('s3')
    path = 's3://{}:{}@{}/datasets/{}'.format(aws_key, aws_secret, bucket_name, title)
    df = pd.read_csv(smart_open(path))
    # df = pd.read_csv(f'media/datasets/{title}')
    df[df.columns[0]] = pd.to_datetime(df[df.columns[0]])
    df.columns = df.columns.str.strip().str.replace(' ','_')
    dateindex = df.columns.values[0]

    #-------------Create tuple pairs for choicefield---------------------
    choicelist = df.columns.values.tolist()
    choicelist2 = choicelist
    choice = list(zip(choicelist,choicelist2))

fyp/templates/project/editplot.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Time Series Data Visualization</title>
  <!-- MDB icon -->
  <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'MDB/css/bootstrap.min.css' %}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{% static 'MDB/css/mdb.min.css' %}">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" type="text/css" href="https://cdn.bokeh.org/bokeh/release/bokeh-1.4.0.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-1.4.0.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.bokeh.org/bokeh/release/bokeh-tables-1.4.0.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
  <style>
  .tab {
	overflow: hidden;
	border: 1px solid #ccc;
	background-color: #f1f1f1;
  }
  
  /* Style the buttons inside the tab */
  .tab button {
	background-color: inherit;
	float: left;
	border: none;
	outline: none;
	cursor: pointer;
	padding: 14px 16px;
	transition: 0.3s;
	font-size: 17px;
  }
  
  /* Change background color of buttons on hover */
  .tab button:hover {
	background-color: #ddd;
  }
  
  /* Create an active/current tablink class */
  .tab button.active {
	background-color: #ccc;
  }
  
  /* Style the tab content */
  .tabcontent {
	display: none;
	padding: 6px 12px;
	border: 1px solid #ccc;
	border-top: none;
  }
  </style>
</head>
<body>

  <!-- Start your project here-->  
  <header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="#">FYP</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
	          <a class="nav-item nav-link" href="{% url 'project:list' user.username %}">Project</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
				{% if user.is_authenticated %}
					<a class="nav-item nav-link" href="{% url 'project:create' %}">New Post</a>
					<a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
				{% else %}
					<a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
					<a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
				{% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-4">
			{% if messages %}
				{% for message in messages %}
					<div class="alert alert-{{ message.tags }}">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
			<div class="content-section">
				<div class="tab">
					<button class="tablinks" onclick="openCity(event, 'Single')" id="One">Single</button>
					<button class="tablinks" onclick="openCity(event, 'Double')" id="Two">Double</button>
				</div>
				<div id="Single" class="tabcontent">
					<form method="POST" action="" class="" enctype="multipart/form-data" id="form">
						{% csrf_token %}
						<fieldset class="form-group">
							<legend class="border-bottom mb-4">Select</legend>
							{{ form | crispy }}
						</fieldset>
						<div class="form-group">
							<button class="btn btn-outline-info" type="submit" value="form" name="createsingle">Create</button>
							<button class="btn btn-outline-info" type="submit" value="Save" name="savesingle">Save</button>
						</div>
					</form>
				</div>

				<div id="Double" class="tabcontent">
					<form method="POST" action="" class="" enctype="multipart/form-data" id="form">
						{% csrf_token %}
						<fieldset class="form-group">
							<legend class="border-bottom mb-4">Select</legend>
							{{ form2 | crispy }}
						</fieldset>
						<div class="form-group">
							<button class="btn btn-outline-info" type="submit" value="form" name="createdouble">Create</button>
							<button class="btn btn-outline-info" type="submit" value="Save" name="savedouble">Save</button>
						</div>
					</form>
				</div>
			</div>
			<a class="float-right btn btn-primary" href="{% url 'project:read' data.project.id %}">Go to Dataset</a>
		</div>
		<div class="card col-md-8" >
            {{div|safe}}
            <div class="card-body">
            {%if currentplot %}
              <h5 class="card-title">{{currentplot.title}}</h5>
              <p class="card-text">{{currentplot.description}}</p>
              <a class="float-right btn btn-outline-danger" href="{% url 'project:plot-delete' currentplot.id %}">Delete</a>
            {%endif%}
            </div>
        </div>
	</div>
  <!-- End your project here-->

  <!-- jQuery -->
  <script type="text/javascript" src="{% static 'MDB/js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'MDB/js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'MDB/js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'MDB/js/mdb.min.js' %}"></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-2.1.0.min.js"></script>
  <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.1.0.min.js"></script>
  <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.1.0.min.js"></script>
  <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.1.0.min.js"></script>
  {{script|safe}}
  <script>
	  document.getElementById("One").click();
	  var selected = '{{type|escapejs}}';
	  console.log(selected)
	  if (selected == 'Single'){
		document.getElementById("One").click();
	  }
	  if(selected == 'Double'){
		document.getElementById("Two").click();
	  }
	  if(selected == 'Bar'){
		document.getElementById("Bar").click();
	  }
	  

	  function openCity(evt, cityName) {
	  var i, tabcontent, tablinks;
	  tabcontent = document.getElementsByClassName("tabcontent");
	  for (i = 0; i < tabcontent.length; i++) {
		tabcontent[i].style.display = "none";
	  }
	  tablinks = document.getElementsByClassName("tablinks");
	  for (i = 0; i < tablinks.length; i++) {
		tablinks[i].className = tablinks[i].className.replace(" active", "");
	  }
	  document.getElementById(cityName).style.display = "block";
	  evt.currentTarget.className += " active";
	}
	</script>

</body>
</html>

fyp/templates/project/plotlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Time Series Data Visualization</title>
  <!-- MDB icon -->
  <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'MDB/css/bootstrap.min.css' %}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{% static 'MDB/css/mdb.min.css' %}">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" type="text/css" href="https://cdn.bokeh.org/bokeh/release/bokeh-1.4.0.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-1.4.0.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.bokeh.org/bokeh/release/bokeh-tables-1.4.0.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
  <style>
  .tab {
	overflow: hidden;
	border: 1px solid #ccc;
	background-color: #f1f1f1;
  }
  
  /* Style the buttons inside the tab */
  .tab button {
	background-color: inherit;
	float: left;
	border: none;
	outline: none;
	cursor: pointer;
	padding: 14px 16px;
	transition: 0.3s;
	font-size: 17px;
  }
  
  /* Change background color of buttons on hover */
  .tab button:hover {
	background-color: #ddd;
  }
  
  /* Create an active/current tablink class */
  .tab button.active {
	background-color: #ccc;
  }
  
  /* Style the tab content */
  .tabcontent {
	display: none;
	padding: 6px 12px;
	border: 1px solid #ccc;
	border-top: none;
  }
  </style>
</head>
<body>

  <!-- Start your project here-->  
  <header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="{% url 'home' %}">FYP</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <!-- <a class="nav-item nav-link" href="{% url 'home' %}">Home</a> -->
	          <a class="nav-item nav-link" href="{% url 'project:list' user.username %}">Project</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
				{% if user.is_authenticated %}
					<a class="nav-item nav-link" href="{% url 'project:create' %}">New Project</a>
					<a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
				{% else %}
					<a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
					<a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
				{% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-4">
			{% if messages %}
				{% for message in messages %}
					<div class="alert alert-{{ message.tags }}">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
			<div class="content-section">
				<h3>Plot List</h3>
				<div class="list-group">
				  {% for plot in plots %}
				  <a href="{% url 'project:view-plot' plot.project.id plot.id%}" class="list-group-item list-group-item-action">{{plot.title}}</a>
				  {% endfor %}
				  <a href="{% url 'project:create-plot' projectid %}" class="list-group-item list-group-item-action"><i class="fas fa-plus"></i> Add Plot</a>
				</div>
			  </div>
			  <a class="float-right btn btn-primary" href="{% url 'project:read' data.project.id %}">Dataset</a>
			  <a class=" btn btn-outline-primary" href="{% url 'project:dashboard' data.project.id %}">Dashboard</a>
			</div>
			<div class="card col-md-8" >
				{{div|safe}}
				<div class="card-body">
				{%if currentplot %}
				  <h5 class="card-title">{{currentplot.title}}</h5>
				  <p class="card-text">{{currentplot.description}}</p>
				  <a class="float-right btn btn-outline-secondary" href="{% url 'project:edit-plot' data.project.id currentplot.id %}">Edit</a>
				  <a class="float-right btn btn-outline-danger" href="{% url 'project:plot-delete' currentplot.id %}">Delete</a>
				{%endif%}
				</div>
			  </div>
			<!-- <div class="col-md-8">
			  {{div|safe}}
			  {%if currentplot %}
			  <a class="float-right btn btn-outline-danger" href="{% url 'project:plot-delete' currentplot.id %}">Delete</a>
			  {{currentplot.description}}
			  {%endif%}
			</div> -->

	</div>
  <!-- End your project here-->

  <!-- jQuery -->
  <script type="text/javascript" src="{% static 'MDB/js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'MDB/js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'MDB/js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'MDB/js/mdb.min.js' %}"></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-2.1.0.min.js"></script>
  <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.1.0.min.js"></script>
  <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.1.0.min.js"></script>
  <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.1.0.min.js"></script>
  {{script|safe}}

fyp/templates/project/project_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" class="">'
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Project</legend>
                <h2>Are you sure you wan to delete the project "{{object.title}}"?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'project:list' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}